language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis
sudo: false
install: true
before_script:
- mvn install -e -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true || true
- mvn install -e -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script: mvn install -e -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
