language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis
sudo: false
install: true
before_script:
- echo "###################\n" && cat /home/travis/.m2/settings.xml
- echo "###################\n" && cat /usr/local/maven/conf/settings.xml
- find /home/travis/.m2/repository
- mvn install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true > /dev/null || true
#- mvn install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
- mvn install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true -pl :spring-boot-dependencies,:spring-boot-parent,:spring-boot-tools,:spring-boot-loader,:spring-boot-loader-tools > /dev/null
- mvn install -X -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true -pl :spring-boot-antlib 
script: mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
