language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis
  - cassandra
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true
jobs:
  include:
    - stage: build-project
      script: ./mvnw -f spring-boot-project/pom.xml clean install -U -Dfull -Dmaven.test.redirectTestOutputToFile=true
    - stage: build-samples-integration-tests
      script: ./mvnw -f spring-boot-samples/pom.xml clean install -U -Dfull
      script: ./mvnw -f spring-boot-tests/spring-boot-integration-tests/pom.xml clean install -U -Dfull
      script: ./mvnw -f spring-boot-tests/spring-boot-deployment-tests/pom.xml clean install -U -Dfull
